"""new_architecture

Revision ID: 6702a6fa81e7
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6702a6fa81e7'
down_revision: Union[str, None] = '61eb98f1369e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='userrole'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='userrole'),
               server_default=sa.text("'user'::userrole"),
               existing_nullable=False)
    # ### end Alembic commands ###

